services:
  juice:
    image: bkimminich/juice-shop:v19.0.0
    container_name: juice11
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx11
    depends_on:
      - juice
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../configs/server.crt:/etc/nginx/certs/server.crt
      - ../configs/server.key:/etc/nginx/certs/server.key
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
