services:
  juice:
    image: bkimminich/juice-shop:v19.0.0
    restart: unless-stopped
    expose:
      - "3000"

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    depends_on:
      - juice
    ports:
      - "8080:80"   # HTTP (will redirect to HTTPS)
      - "8443:443"   # HTTPS
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./reverse-proxy/certs:/etc/nginx/certs:ro
      - ./logs:/var/log/nginx:rw
